{"level":"error","message":"Failed to setup bot: setupMessageHandlers is not a function","stack":"TypeError: setupMessageHandlers is not a function\n    at setupBot (D:\\Kaser\\src\\core\\bot.js:8:9)\n    at startBot (D:\\Kaser\\src\\index.js:16:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-01-21T01:04:59.706Z"}
{"_message":"Cache validation failed","errors":{"expiresAt":{"kind":"required","message":"Path `expiresAt` is required.","name":"ValidatorError","path":"expiresAt","properties":{"message":"Path `expiresAt` is required.","path":"expiresAt","type":"required"}}},"level":"error","message":"Error processing voice: Cache validation failed: expiresAt: Path `expiresAt` is required.","stack":"ValidationError: Cache validation failed: expiresAt: Path `expiresAt` is required.\n    at Document.invalidate (D:\\Kaser\\node_modules\\mongoose\\lib\\document.js:3334:32)\n    at D:\\Kaser\\node_modules\\mongoose\\lib\\document.js:3095:17\n    at D:\\Kaser\\node_modules\\mongoose\\lib\\schemaType.js:1407:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)","timestamp":"2025-01-21T01:06:06.825Z"}
{"level":"error","message":"Error in handleVoice: processingMessage.delete is not a function","stack":"TypeError: processingMessage.delete is not a function\n    at handleVoice (D:\\Kaser\\src\\workers\\message\\voice.js:118:43)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async D:\\Kaser\\src\\workers\\message\\index.js:47:13\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:519:21\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:519:21\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:519:21\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)","timestamp":"2025-01-21T01:06:06.830Z"}
{"kind":"number","level":"error","message":"Error processing voice: Cast to number failed for value \"undefined\" (type undefined) at path \"stats.tokenUsage\"","path":"stats.tokenUsage","stack":"CastError: Cast to number failed for value \"undefined\" (type undefined) at path \"stats.tokenUsage\"\n    at castUpdateVal (D:\\Kaser\\node_modules\\mongoose\\lib\\helpers\\query\\castUpdate.js:581:13)\n    at walkUpdatePath (D:\\Kaser\\node_modules\\mongoose\\lib\\helpers\\query\\castUpdate.js:423:24)\n    at castUpdate (D:\\Kaser\\node_modules\\mongoose\\lib\\helpers\\query\\castUpdate.js:134:7)\n    at model.Query._castUpdate (D:\\Kaser\\node_modules\\mongoose\\lib\\query.js:4685:10)\n    at model.Query._updateThunk (D:\\Kaser\\node_modules\\mongoose\\lib\\query.js:3878:25)\n    at model.Query._updateOne (D:\\Kaser\\node_modules\\mongoose\\lib\\query.js:3966:23)\n    at model.Query.exec (D:\\Kaser\\node_modules\\mongoose\\lib\\query.js:4438:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async handleVoice (D:\\Kaser\\src\\workers\\message\\voice.js:106:13)\n    at async D:\\Kaser\\src\\workers\\message\\index.js:47:13","stringValue":"\"undefined\"","timestamp":"2025-01-21T01:08:58.806Z","valueType":"undefined"}
{"kind":"number","level":"error","message":"Error in handleVoice: Cast to number failed for value \"undefined\" (type undefined) at path \"stats.tokenUsage\"","path":"stats.tokenUsage","stack":"CastError: Cast to number failed for value \"undefined\" (type undefined) at path \"stats.tokenUsage\"\n    at castUpdateVal (D:\\Kaser\\node_modules\\mongoose\\lib\\helpers\\query\\castUpdate.js:581:13)\n    at walkUpdatePath (D:\\Kaser\\node_modules\\mongoose\\lib\\helpers\\query\\castUpdate.js:423:24)\n    at castUpdate (D:\\Kaser\\node_modules\\mongoose\\lib\\helpers\\query\\castUpdate.js:134:7)\n    at model.Query._castUpdate (D:\\Kaser\\node_modules\\mongoose\\lib\\query.js:4685:10)\n    at model.Query._updateThunk (D:\\Kaser\\node_modules\\mongoose\\lib\\query.js:3878:25)\n    at model.Query._updateOne (D:\\Kaser\\node_modules\\mongoose\\lib\\query.js:3966:23)\n    at model.Query.exec (D:\\Kaser\\node_modules\\mongoose\\lib\\query.js:4438:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async handleVoice (D:\\Kaser\\src\\workers\\message\\voice.js:106:13)\n    at async D:\\Kaser\\src\\workers\\message\\index.js:47:13","stringValue":"\"undefined\"","timestamp":"2025-01-21T01:08:58.920Z","valueType":"undefined"}
{"level":"error","message":"Failed to connect to MongoDB: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"kaser-shard-00-00.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-00.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":24770894,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"kaser-shard-00-01.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-01.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":24770895,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"kaser-shard-00-02.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-02.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":24771009,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":"atlas-10q11d-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1110:11)\n    at NativeConnection.openUri (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1041:11)\n    at async setupDatabase (D:\\Kaser\\src\\database\\connections.js:6:9)\n    at async startBot (D:\\Kaser\\src\\index.js:13:9)","timestamp":"2025-01-21T22:45:40.636Z"}
{"level":"error","message":"Failed to connect to MongoDB: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"kaser-shard-00-00.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-00.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":24807348,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"kaser-shard-00-01.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-01.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":24808111,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"kaser-shard-00-02.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-02.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":24808014,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":"atlas-10q11d-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1110:11)\n    at NativeConnection.openUri (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1041:11)\n    at async setupDatabase (D:\\Kaser\\src\\database\\connections.js:6:9)\n    at async startBot (D:\\Kaser\\src\\index.js:13:9)","timestamp":"2025-01-21T22:46:17.373Z"}
{"level":"error","message":"Failed to connect to MongoDB: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"kaser-shard-00-00.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-00.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":24847438,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"kaser-shard-00-01.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-01.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":24847670,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"kaser-shard-00-02.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-02.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":24847394,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":"atlas-10q11d-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1110:11)\n    at NativeConnection.openUri (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1041:11)\n    at async setupDatabase (D:\\Kaser\\src\\database\\connections.js:6:9)\n    at async startBot (D:\\Kaser\\src\\index.js:13:9)","timestamp":"2025-01-21T22:46:57.245Z"}
{"level":"error","message":"Failed to connect to MongoDB: getaddrinfo ENOTFOUND mongodb.railway.internal","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"mongodb.railway.internal:27017":{"$clusterTime":null,"address":"mongodb.railway.internal:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":25419466,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":null,"stale":false,"type":"Unknown"},"stack":"MongooseServerSelectionError: getaddrinfo ENOTFOUND mongodb.railway.internal\n    at _handleConnectionErrors (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1110:11)\n    at NativeConnection.openUri (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1041:11)\n    at async setupDatabase (D:\\Kaser\\src\\database\\connections.js:6:9)\n    at async startBot (D:\\Kaser\\src\\index.js:13:9)","timestamp":"2025-01-21T22:56:29.075Z"}
{"code":18,"codeName":"AuthenticationFailed","connectionGeneration":0,"errorResponse":{"code":18,"codeName":"AuthenticationFailed","errmsg":"Authentication failed.","ok":0},"level":"error","message":"Failed to connect to MongoDB: Authentication failed.","ok":0,"stack":"MongoServerError: Authentication failed.\n    at Connection.sendCommand (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\connection.js:296:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Connection.command (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\connection.js:323:26)\n    at async executeScram (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\auth\\scram.js:79:22)\n    at async ScramSHA256.auth (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\auth\\scram.js:39:16)\n    at async performInitialHandshake (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\connect.js:104:13)\n    at async connect (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\connect.js:24:9)","timestamp":"2025-01-21T22:58:24.594Z"}
{"code":18,"codeName":"AuthenticationFailed","connectionGeneration":0,"errorResponse":{"code":18,"codeName":"AuthenticationFailed","errmsg":"Authentication failed.","ok":0},"level":"error","message":"Failed to connect to MongoDB: Authentication failed.","ok":0,"stack":"MongoServerError: Authentication failed.\n    at Connection.sendCommand (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\connection.js:296:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Connection.command (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\connection.js:323:26)\n    at async executeScram (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\auth\\scram.js:79:22)\n    at async ScramSHA256.auth (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\auth\\scram.js:39:16)\n    at async performInitialHandshake (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\connect.js:104:13)\n    at async connect (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\connect.js:24:9)","timestamp":"2025-01-21T23:00:22.828Z"}
{"code":18,"codeName":"AuthenticationFailed","connectionGeneration":0,"errorResponse":{"code":18,"codeName":"AuthenticationFailed","errmsg":"Authentication failed.","ok":0},"level":"error","message":"Failed to connect to MongoDB: Authentication failed.","ok":0,"stack":"MongoServerError: Authentication failed.\n    at Connection.sendCommand (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\connection.js:296:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Connection.command (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\connection.js:323:26)\n    at async executeScram (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\auth\\scram.js:79:22)\n    at async ScramSHA256.auth (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\auth\\scram.js:39:16)\n    at async performInitialHandshake (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\connect.js:104:13)\n    at async connect (D:\\Kaser\\node_modules\\mongodb\\lib\\cmap\\connect.js:24:9)","timestamp":"2025-01-21T23:04:39.026Z"}
{"level":"error","message":"Failed to connect to MongoDB: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"kaser-shard-00-00.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-00.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":25996006,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"kaser-shard-00-01.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-01.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":25995642,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"kaser-shard-00-02.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-02.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":{},"hosts":[],"iscryptd":false,"lastUpdateTime":25995698,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":"atlas-10q11d-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1110:11)\n    at NativeConnection.openUri (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1041:11)\n    at async setupDatabase (D:\\Kaser\\src\\database\\connections.js:6:9)\n    at async startBot (D:\\Kaser\\src\\index.js:13:9)","timestamp":"2025-01-21T23:06:05.505Z"}
{"level":"error","message":"Failed to connect to MongoDB: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"kaser-shard-00-00.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-00.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":null,"hosts":[],"iscryptd":false,"lastUpdateTime":26332904,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"kaser-shard-00-01.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-01.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":null,"hosts":[],"iscryptd":false,"lastUpdateTime":26332904,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"kaser-shard-00-02.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-02.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":null,"hosts":[],"iscryptd":false,"lastUpdateTime":26332903,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":"atlas-10q11d-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1110:11)\n    at NativeConnection.openUri (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1041:11)\n    at async setupDatabase (D:\\Kaser\\src\\database\\connections.js:6:9)\n    at async startBot (D:\\Kaser\\src\\index.js:13:9)","timestamp":"2025-01-21T23:11:47.254Z"}
{"level":"error","message":"Failed to connect to MongoDB: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"kaser-shard-00-00.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-00.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":null,"hosts":[],"iscryptd":false,"lastUpdateTime":26362518,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"kaser-shard-00-01.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-01.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":null,"hosts":[],"iscryptd":false,"lastUpdateTime":26362518,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"kaser-shard-00-02.y0ewo.mongodb.net:27017":{"$clusterTime":null,"address":"kaser-shard-00-02.y0ewo.mongodb.net:27017","arbiters":[],"electionId":null,"error":null,"hosts":[],"iscryptd":false,"lastUpdateTime":26362518,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":"atlas-10q11d-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1110:11)\n    at NativeConnection.openUri (D:\\Kaser\\node_modules\\mongoose\\lib\\connection.js:1041:11)\n    at async setupDatabase (D:\\Kaser\\src\\database\\connections.js:6:9)\n    at async startBot (D:\\Kaser\\src\\index.js:13:9)","timestamp":"2025-01-21T23:12:16.856Z"}
{"level":"error","message":"Error in handleText: No matching document found for id \"678ec4e1d495ad8e183e39b5\" version 77 modifiedPaths \"messages\"","modifiedPaths":["messages"],"stack":"VersionError: No matching document found for id \"678ec4e1d495ad8e183e39b5\" version 77 modifiedPaths \"messages\"\n    at generateVersionError (D:\\Kaser\\node_modules\\mongoose\\lib\\model.js:517:10)\n    at model.save (D:\\Kaser\\node_modules\\mongoose\\lib\\model.js:575:28)\n    at handleText (D:\\Kaser\\src\\workers\\message\\text.js:99:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async D:\\Kaser\\src\\workers\\message\\index.js:25:13\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:519:21\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)","timestamp":"2025-01-21T23:24:48.102Z","version":77}
{"level":"error","message":"Error in handleText: No matching document found for id \"678ec4e1d495ad8e183e39b5\" version 77 modifiedPaths \"messages\"","modifiedPaths":["messages"],"stack":"VersionError: No matching document found for id \"678ec4e1d495ad8e183e39b5\" version 77 modifiedPaths \"messages\"\n    at generateVersionError (D:\\Kaser\\node_modules\\mongoose\\lib\\model.js:517:10)\n    at model.save (D:\\Kaser\\node_modules\\mongoose\\lib\\model.js:575:28)\n    at handleText (D:\\Kaser\\src\\workers\\message\\text.js:99:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async D:\\Kaser\\src\\workers\\message\\index.js:25:13\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:519:21\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)","timestamp":"2025-01-21T23:24:48.201Z","version":77}
{"level":"error","message":"Error in handleText: No matching document found for id \"67902d5909087eecaac57ebb\" version 3 modifiedPaths \"messages\"","modifiedPaths":["messages"],"stack":"VersionError: No matching document found for id \"67902d5909087eecaac57ebb\" version 3 modifiedPaths \"messages\"\n    at generateVersionError (D:\\Kaser\\node_modules\\mongoose\\lib\\model.js:517:10)\n    at model.save (D:\\Kaser\\node_modules\\mongoose\\lib\\model.js:575:28)\n    at handleText (D:\\Kaser\\src\\workers\\message\\text.js:99:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async D:\\Kaser\\src\\workers\\message\\index.js:25:13\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:519:21\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)","timestamp":"2025-01-21T23:27:28.818Z","version":3}
{"error":{},"level":"error","message":"Error getting group context","timestamp":"2025-01-21T23:53:23.748Z"}
{"error":{},"level":"error","message":"Error getting group context","timestamp":"2025-01-21T23:53:43.525Z"}
{"error":{},"level":"error","message":"Error getting group context","timestamp":"2025-01-21T23:54:11.161Z"}
{"error":{},"level":"error","message":"Error getting group context","timestamp":"2025-01-21T23:54:24.601Z"}
{"code":"model_not_found","error":{"code":"model_not_found","message":"Project `proj_xixi24RMpT7NuUV76gbAHKyZ` does not have access to model `gpt-4-1106-preview`","param":null,"type":"invalid_request_error"},"headers":{"alt-svc":"h3=\":443\"; ma=86400","cf-cache-status":"DYNAMIC","cf-ray":"905b4641699290fe-FRA","connection":"keep-alive","content-encoding":"gzip","content-type":"application/json; charset=utf-8","date":"Wed, 22 Jan 2025 00:02:18 GMT","server":"cloudflare","set-cookie":"__cf_bm=oTcP8H4IA32oWOGC7iAPHm0A4bX7grgzEaJccSSqY8Y-1737504138-1.0.1.1-mn79v85sZ8pSqUE37XVv8VGhuBxXmG3sjUTBkHFkTsRoFIzfEk5_pFSeQt5iFNBSaYRY20GZ3jADxskcb33Vxg; path=/; expires=Wed, 22-Jan-25 00:32:18 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=UQ1e02rldRhxRet9z7mBhuvwmo5Gu54Zj0wBFpK36BY-1737504138641-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=31536000; includeSubDomains; preload","transfer-encoding":"chunked","vary":"Origin","x-content-type-options":"nosniff","x-request-id":"req_6314586e036016e9a912a21d58ae6778"},"level":"error","message":"Error in processWithGPT: 403 Project `proj_xixi24RMpT7NuUV76gbAHKyZ` does not have access to model `gpt-4-1106-preview`","param":null,"request_id":"req_6314586e036016e9a912a21d58ae6778","stack":"Error: 403 Project `proj_xixi24RMpT7NuUV76gbAHKyZ` does not have access to model `gpt-4-1106-preview`\n    at APIError.generate (D:\\Kaser\\node_modules\\openai\\error.js:51:20)\n    at OpenAI.makeStatusError (D:\\Kaser\\node_modules\\openai\\core.js:293:33)\n    at OpenAI.makeRequest (D:\\Kaser\\node_modules\\openai\\core.js:337:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async processWithGPT (D:\\Kaser\\src\\services\\ai\\gpt\\client.js:123:28)\n    at async handleText (D:\\Kaser\\src\\workers\\message\\text.js:90:26)\n    at async D:\\Kaser\\src\\workers\\message\\index.js:25:13\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)\n    at async D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:519:21\n    at async execute (D:\\Kaser\\node_modules\\telegraf\\lib\\composer.js:518:17)","status":403,"timestamp":"2025-01-22T00:02:18.495Z","type":"invalid_request_error"}
{"code":11000,"errorResponse":{"code":11000,"errmsg":"E11000 duplicate key error collection: test.caches index: key_1 dup key: { key: \"greeting:مرحبا\" }","index":0,"keyPattern":{"key":1},"keyValue":{"key":"greeting:مرحبا"}},"index":0,"keyPattern":{"key":1},"keyValue":{"key":"greeting:مرحبا"},"level":"error","message":"Error in processWithGPT: E11000 duplicate key error collection: test.caches index: key_1 dup key: { key: \"greeting:مرحبا\" }","stack":"MongoServerError: E11000 duplicate key error collection: test.caches index: key_1 dup key: { key: \"greeting:مرحبا\" }\n    at InsertOneOperation.execute (D:\\Kaser\\node_modules\\mongodb\\lib\\operations\\insert.js:51:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async tryOperation (D:\\Kaser\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:203:20)\n    at async executeOperation (D:\\Kaser\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:73:16)\n    at async Collection.insertOne (D:\\Kaser\\node_modules\\mongodb\\lib\\collection.js:157:16)","timestamp":"2025-01-22T00:09:27.656Z"}
{"code":11000,"errorResponse":{"code":11000,"errmsg":"E11000 duplicate key error collection: test.caches index: key_1 dup key: { key: \"greeting:مرحبا\" }","index":0,"keyPattern":{"key":1},"keyValue":{"key":"greeting:مرحبا"}},"index":0,"keyPattern":{"key":1},"keyValue":{"key":"greeting:مرحبا"},"level":"error","message":"Error in processWithGPT: E11000 duplicate key error collection: test.caches index: key_1 dup key: { key: \"greeting:مرحبا\" }","stack":"MongoServerError: E11000 duplicate key error collection: test.caches index: key_1 dup key: { key: \"greeting:مرحبا\" }\n    at InsertOneOperation.execute (D:\\Kaser\\node_modules\\mongodb\\lib\\operations\\insert.js:51:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async tryOperation (D:\\Kaser\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:203:20)\n    at async executeOperation (D:\\Kaser\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:73:16)\n    at async Collection.insertOne (D:\\Kaser\\node_modules\\mongodb\\lib\\collection.js:157:16)","timestamp":"2025-01-22T00:10:56.214Z"}
{"code":11000,"errorResponse":{"code":11000,"errmsg":"E11000 duplicate key error collection: test.caches index: key_1 dup key: { key: \"greeting:مرحبا\" }","index":0,"keyPattern":{"key":1},"keyValue":{"key":"greeting:مرحبا"}},"index":0,"keyPattern":{"key":1},"keyValue":{"key":"greeting:مرحبا"},"level":"error","message":"Error in processWithGPT: E11000 duplicate key error collection: test.caches index: key_1 dup key: { key: \"greeting:مرحبا\" }","stack":"MongoServerError: E11000 duplicate key error collection: test.caches index: key_1 dup key: { key: \"greeting:مرحبا\" }\n    at InsertOneOperation.execute (D:\\Kaser\\node_modules\\mongodb\\lib\\operations\\insert.js:51:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async tryOperation (D:\\Kaser\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:203:20)\n    at async executeOperation (D:\\Kaser\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:73:16)\n    at async Collection.insertOne (D:\\Kaser\\node_modules\\mongodb\\lib\\collection.js:157:16)","timestamp":"2025-01-22T00:11:01.793Z"}
